-- MySQL Script generated by MySQL Workbench
-- Fri Aug 22 11:42:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_management` DEFAULT CHARACTER SET utf8mb4 ;
USE `hotel_management` ;

-- -----------------------------------------------------
-- Table `hotel_management`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`department` (
  `department_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `head` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `staff_count` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`staff` (
  `staff_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `contact_info` VARCHAR(255) NULL DEFAULT NULL,
  `salary` DECIMAL(10,2) NULL DEFAULT NULL,
  `department_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `department_id` (`department_id` ASC) VISIBLE,
  CONSTRAINT `staff_ibfk_1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hotel_management`.`department` (`department_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`actionlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`actionlog` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `staff_id` INT(11) NULL DEFAULT NULL,
  `action_type` ENUM('create', 'update', 'delete', 'login', 'logout') NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `action_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `actionlog_ibfk_1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `hotel_management`.`staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`permission` (
  `permission_id` INT(11) NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`permission_id`),
  UNIQUE INDEX `permission_name` (`permission_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`rolepermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`rolepermission` (
  `role_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  UNIQUE INDEX `rolepermission_permission_id_role_id_unique` (`role_id` ASC, `permission_id` ASC) VISIBLE,
  UNIQUE INDEX `rolepermission_role_id_permission_id` (`role_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `permission_id` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `rolepermission_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `hotel_management`.`role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `rolepermission_ibfk_2`
    FOREIGN KEY (`permission_id`)
    REFERENCES `hotel_management`.`permission` (`permission_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `staff_id` INT(11) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `staff_id` (`staff_id` ASC) VISIBLE,
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `hotel_management`.`staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotel_management`.`userrole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management`.`userrole` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  UNIQUE INDEX `UserRole_role_id_user_id_unique` (`user_id` ASC, `role_id` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `userrole_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hotel_management`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userrole_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `hotel_management`.`role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
